apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermicroservice
spec:
  selector:
    matchLabels:
      app: usermicroservice
  replicas: 1
  template:
    metadata:
      labels:
        app: usermicroservice
    spec:
      containers:
      - name: usermicroservice
        image: gcr.io/engaged-plasma-389007/lux4899/test:2
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
